version: ~> 1.0
services:
  - docker

language: minimal

git:
  lfs_skip_smudge: true

env:
  - TAG=gcc
  - TAG=afl

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - docker pull unifuzz/unibench:$TAG || true
  - cd $TAG && docker build --cache-from unifuzz/unibench:$TAG -t unifuzz/unibench:$TAG .

deploy:
  provider: script
  script:
    - docker push unifuzz/unibench:$TAG
