sudo: required
services:
  - docker

before_install:
  - git clone https://github.com/zjuchenyuan/dockerized_fuzzing

install:
  - cd dockerized_fuzzing/afl && docker build -t zjuchenyuan/afl:unibench -f Dockerfile.unibench .

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push zjuchenyuan/afl:unibench
