version: ~> 1.0
services:
  - docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - git clone https://github.com/zjuchenyuan/dockerized_fuzzing

install:
  - cd dockerized_fuzzing/afl && docker build -t unifuzz/unibench:afl -f Dockerfile.unibench .

deploy:
  provider: script
  script:
    - docker push unifuzz/unibench:afl
