version: ~> 1.0
services:
  - docker

env:
  - TAG=gcc
  - TAG=afl

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - docker pull unifuzz/unibench:$TAG
  - cd $TAG && docker build -t unifuzz/unibench:$TAG .

deploy:
  provider: script
  script:
    - docker push unifuzz/unibench:$TAG
