version: ~> 1.0
services:
  - docker

language: minimal

git:
  lfs_skip_smudge: true

env:
  - TAG=gcc
  - TAG=afl
  - TAG=aflfast
  - TAG=honggfuzz
  - TAG=vuzzer
  - TAG=angora_step1
  - TAG=angora_step2
  - TAG=angora
  - TAG=coverage

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

install:
  - mkdir -p /tmp/dockercache && md5sum -c /tmp/dockercache/$TAG && exit 0
  - docker pull unifuzz/unibench:$TAG || true
  - cd $TAG && docker build --cache-from unifuzz/unibench:$TAG -t unifuzz/unibench:$TAG . && cd .. && md5sum ${TAG}/Dockerfile > /tmp/dockercache/$TAG

deploy:
  provider: script
  script: docker push unifuzz/unibench:$TAG

cache:
  directories:
    - /tmp/dockercache